cloth/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),  # Замените 'store' на имя вашего приложения
]

store/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import *

urlpatterns = [
    path('', all_products, name='all_products'),
    path('product_list', ProductView.as_view(), name='product_list'),
    path('create_order', OrderCreateView.as_view(), name='create_order'),
    path('all_products', all_products, name='all_products'),
    path('products_by_tag/<str:tag_name>', products_by_tag, name='products_by_tag'),
]

store/models.py
from django.db import models

class CustomerCL(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name


class TagCL(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class ProductCL(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    tags = models.ManyToManyField(TagCL)

    def __str__(self):
        return self.name


class OrderCL(models.Model):
    customer = models.ForeignKey(CustomerCL, on_delete=models.CASCADE)
    products = models.ManyToManyField(ProductCL)
    order_date = models.DateField(auto_now_add=True)

store/forms.py
from django import forms
from .models import OrderCL, ProductCL

class OrderForm(forms.ModelForm):
    class Meta:
        model = OrderCL
        fields = '__all__'

store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, ListView
from .models import *

from .forms import OrderForm

def all_products(request):
    tags = TagCL.objects.all()
    return render(request, 'all_products.html', {'tags': tags})


class ProductView(ListView):
    model = ProductCL
    queryset = ProductCL.objects.all()
    template_name = 'product_list.html'


class TagsView(ListView):
    model = TagCL
    queryset = TagCL.objects.all()
    context_object_name = 'tags'
    template_name = 'all_products.html'


class OrderCreateView(CreateView):
    model = OrderCL
    form_class = OrderForm
    success_url = '/'
    template_name = 'create_order.html'


def products_by_tag(request, tag_name):
    products = ProductCL.objects.filter(tags__name__icontains=tag_name)
    context = {'products': products, 'tag': tag_name}
    return render(request, 'products_by_tag.html', context)

def show_error_page(request):
    return render(request, "error.html")

templates/all_products.html
<!DOCTYPE html>
<html>
<head>
    <title>All Products</title>
</head>
<body>



{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Cloth</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="../../static/img/logoss.png">
    <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
        <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


    <!-- CSS here -->
<!--    <link rel="stylesheet" href="/css/bootstrap.min.css">-->
<!--    <link rel="stylesheet" href="../../static/css/owl.carousel.min.css">-->
</head>

<body>
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-3">
                            <div class="logo">
                                <a href="products.html">
                                    <img src="../../static/img/logoss.png" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-9 col-lg-9">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="/product_list">Products Details</a></li>
                                        <li><a href="/create_order">Create Order</a></li>
                                        {% for i in tags%}
                                            <li><a href="products_by_tag/{{i.name}}">{{i.name}}</a></li>
                                        {% endfor %}
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <!-- footer_start  -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget">
                            <h3 class="footer_title">
                                Contact Us
                            </h3>
                            <ul class="address_line">
                                <li>+9493839320</li>
                                <li><a href="#">Nobodycares@gmail.Com</a></li>
                                <li>Bishkek</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text">
            <div class="container">
                <div class="bordered_1px"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright Salim</p>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer_end  -->


    <!-- JS here -->
    <script src="../../static/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="../../static/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="../../static/js/popper.min.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>
    <script src="../../static/js/owl.carousel.min.js"></script>
    <script src="../../static/js/isotope.pkgd.min.js"></script>
    <script src="../../static/js/ajax-form.js"></script>
    <script src="../../static/js/waypoints.min.js"></script>
    <script src="../../static/js/jquery.counterup.min.js"></script>
    <script src="../../static/js/imagesloaded.pkgd.min.js"></script>
    <script src="../../static/js/scrollIt.js"></script>
    <script src="../../static/js/jquery.scrollUp.min.js"></script>
    <script src="../../static/js/wow.min.js"></script>
    <script src="../../static/js/nice-select.min.js"></script>
    <script src="../../static/js/jquery.slicknav.min.js"></script>
    <script src="../../static/js/jquery.magnific-popup.min.js"></script>
    <script src="../../static/js/plugins.js"></script>
    <script src="../../static/js/gijgo.min.js"></script>

    <!--contact js-->
    <script src="../../static/js/contact.js"></script>
    <script src="../../static/js/jquery.ajaxchimp.min.js"></script>
    <script src="../../static/js/jquery.form.js"></script>
    <script src="../../static/js/jquery.validate.min.js"></script>
    <script src="../../static/js/mail-script.js"></script>

    <script src="../../static/js/main.js"></script>
    <script>
        $('#datepicker').datepicker({
            iconsLibrary: 'fontawesome',
            disableDaysOfWeek: [0, 0],
        //     icons: {
        //      rightIcon: '<span class="fa fa-caret-down"></span>'
        //  }
        });
        $('#datepicker2').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
             rightIcon: '<span class="fa fa-caret-down"></span>'
         }

        });
        var timepicker = $('#timepicker').timepicker({
         format: 'HH.MM'
     });
    </script>
</body>

</html>

templates/create_order.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Order</title>
</head>
<body>
    <h2>Create Order</h2>
    <form method="post" action="{% url 'create_order' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Order</button>
    </form>
</body>
</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cloth</title>
</head>
<body>
<center><h1>UPS!</h1></center>
</body>
</html>

templates/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  {% for i in productcl_list %}
        <p>{{i.name}}</p>
        <p>{{i.description}}</p>
        <p>{{i.price}}</p>
        <p>{{i.tags}}</p>
  {% endfor %}
</body>
</html>

templates/products.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Book</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="../../static/img/logoss.png">
    <!-- Place favicon.ico in the root directory -->

        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
        <link rel="stylesheet" href="{% static 'css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
        <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
        <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


    <!-- CSS here -->
<!--    <link rel="stylesheet" href="/css/bootstrap.min.css">-->
<!--    <link rel="stylesheet" href="../../static/css/owl.carousel.min.css">-->
</head>

<body>
    <header>
        <div class="header-area ">      
            <div id="sticky-header" class="main-header-area">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-3">
                            <div class="logo">
                                <a href="products.html">
                                    <img src="../../static/img/logoss.png" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-9 col-lg-9">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="/product_list">Products Details</a></li>
                                        <li><a href="/all_product/">Only products</a></li>
                                        <li><a href="/products_by_tag/">Tag</a></li>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

<!--================Blog Area =================-->
<section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5 mb-lg-0">
                <div class="blog_left_sidebar">
                    <article class="blog_item">
                        <div class="blog_item_img">
                            <img class="card-img rounded-0" src="../../static/img/blog/single_blog.png" alt="">
                        </div>

                        <div class="blog_details">
                                <ul>
                                    {%for i in book_key%}
                                    <li>
                                        <h1>{{i.title}}</h1>
                                        <p>{{i.created_date}}</p>
                                        <button><a href="/book_detail/{{i.id}}">Next</a></button>
                                    </li>
                                    {% endfor %}
                                </ul>
                        </div>
                    </article>

                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget search_widget">
                        <form action="{% url 'search' %}" method="get" class="d-flex" role="search">
                            <div class="form-group">
                                <div class="input-group mb-3" >
                                    <input type="search" name="search" class="form-control" placeholder='Search Keyword'
                                        onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Search Keyword'">
                                </div>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn" for="search"
                                type="submit">Search</button>
                        </form>
                    </aside>

                    <aside class="single_sidebar_widget post_category_widget">
                        <h4 class="widget_title">Category</h4>
                        <ul class="list cat-list">
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Fantasy</p>
                                    <p>(37)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Action</p>
                                    <p>(10)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Documentary</p>
                                    <p>(03)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Detective</p>
                                    <p>(11)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Fairies</p>
                                    <p>21</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Adventure</p>
                                    <p>09</p>
                                </a>
                            </li>
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================Blog Area =================-->

    <!-- footer_start  -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget">
                            <h3 class="footer_title">
                                Contact Us
                            </h3>
                            <ul class="address_line">
                                <li>+9493839320</li>
                                <li><a href="#">Nobodycares@gmail.Com</a></li>
                                <li>Bishkek</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-3  col-md-6 col-lg-3">
                        <div class="footer_widget">
                            <h3 class="footer_title">
                                Our Servces
                            </h3>
                        </div>
                    </div>
                    <div class="col-xl-3  col-md-6 col-lg-3">
                        <div class="footer_widget">
                            <h3 class="footer_title">
                                Quick Link
                            </h3>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3 ">
                        <div class="footer_widget">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="../../static/img/logoss.png" alt="">
                                </a>
                            </div>
                            <p class="address_text">Bishkek
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="ti-pinterest"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-linkedin"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text">
            <div class="container">
                <div class="bordered_1px"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright Salim</p>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer_end  -->


    <!-- JS here -->
    <script src="../../static/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="../../static/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="../../static/js/popper.min.js"></script>
    <script src="../../static/js/bootstrap.min.js"></script>
    <script src="../../static/js/owl.carousel.min.js"></script>
    <script src="../../static/js/isotope.pkgd.min.js"></script>
    <script src="../../static/js/ajax-form.js"></script>
    <script src="../../static/js/waypoints.min.js"></script>
    <script src="../../static/js/jquery.counterup.min.js"></script>
    <script src="../../static/js/imagesloaded.pkgd.min.js"></script>
    <script src="../../static/js/scrollIt.js"></script>
    <script src="../../static/js/jquery.scrollUp.min.js"></script>
    <script src="../../static/js/wow.min.js"></script>
    <script src="../../static/js/nice-select.min.js"></script>
    <script src="../../static/js/jquery.slicknav.min.js"></script>
    <script src="../../static/js/jquery.magnific-popup.min.js"></script>
    <script src="../../static/js/plugins.js"></script>
    <script src="../../static/js/gijgo.min.js"></script>

    <!--contact js-->
    <script src="../../static/js/contact.js"></script>
    <script src="../../static/js/jquery.ajaxchimp.min.js"></script>
    <script src="../../static/js/jquery.form.js"></script>
    <script src="../../static/js/jquery.validate.min.js"></script>
    <script src="../../static/js/mail-script.js"></script>

    <script src="../../static/js/main.js"></script>
    <script>
        $('#datepicker').datepicker({
            iconsLibrary: 'fontawesome',
            disableDaysOfWeek: [0, 0],
        //     icons: {
        //      rightIcon: '<span class="fa fa-caret-down"></span>'
        //  }
        });
        $('#datepicker2').datepicker({
            iconsLibrary: 'fontawesome',
            icons: {
             rightIcon: '<span class="fa fa-caret-down"></span>'
         }

        });
        var timepicker = $('#timepicker').timepicker({
         format: 'HH.MM'
     });
    </script>
</body>

</html>

templates/products_by_tag.html
<!DOCTYPE html>
<html>
<head>
    <title>Products by Tag</title>
</head>
<body>
       <h2>Products with tag {{tag}} </h2>
      {% for i in products %}
        <h1>{{i.name}}</h1>
      {% endfor %}
</body>
</html>